/* --- OBJECTS --- */

export const ErrorCodes = {
    REQUIRED: "REQUIRED",
    INVALID_FORMAT: "INVALID_FORMAT",
    INVALID_USERNAME: "INVALID_USERNAME",
    INVALID_EMAIL: "INVALID_EMAIL",
    WEAK_PASSWORD: "WEAK_PASSWORD",
    DATE_TOO_YOUNG: "DATE_TOO_YOUNG",
    INVALID_CAP: "INVALID_CAP",
    INVALID_CREDIT: "INVALID_CREDIT",
    MUNICIPALITY_REQUIRED: "MUNICIPALITY_REQUIRED",
} as const;

/* --- TYPES --- */

export type ValidationErrorCode = typeof ErrorCodes[keyof typeof ErrorCodes];